name: Build Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build_feature:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
            testExe: build/sst-voicemanager-test
          - os: macos-latest
            name: mac
            testExe: build/sst-voicemanager-test
          - os: windows-latest
            name: win
            testExe: build/Release/sst-voicemanager-test.exe

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: pick GCC12
        if: runner.os == 'Linux'
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 12
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 12

      - name: Build test
        run: |
          cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release -DSST_VOICEMANAGER_BUILD_TESTS=TRUE 
          cmake --build ./build --config Release

      - name: Run test
        run: |
          ls ${{ matrix.testExe }}
          ${{ matrix.testExe }}


  build_test_docker:
    name: Test - Docker Ubuntu 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build in Docker
        uses: surge-synthesizer/sst-githubactions/cmake-in-docker@main
        with:
          image: ghcr.io/surge-synthesizer/sst-dockerimages/ubuntu20_gcc11:main
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          cmakeArgs: -DCMAKE_BUILD_TYPE=Release -DSST_VOICEMANAGER_BUILD_TESTS=TRUE
          target: sst-voicemanager-test

      - name: Run Test
        run: |
          ls -l build/tests
          ./build/sst-voicemanager-tests
